from environs import Env

env = Env()
env.read_env()

GIA_WEBSITE_KEY = env.str('GIA_WEBSITE_KEY')
GIA_ENTRY_URL = env.str('GIA_ENTRY_URL')
GIA_VERIFY_URL = env.str('GIA_VERIFY_URL')

YESCAPTCHA_CLIENT_KEY = env.str('YESCAPTCHA_CLIENT_KEY')
YESCAPTCHA_TASK_URL = env.str("YESCAPTCHA_TASK_URL")
YESCAPTCHA_RESPONSE_URL = env.str("YESCAPTCHA_RESPONSE_URL")